# 예외처리

* 여러 Exception이 발생하여 프로그램이 비정상적으로 종료되지 않도록
*  NullPointerException, ClassCastException,  ArrayIndexOutOfBoundsException 등
* 이러한 Exception은 컴파일 후에, 그 줄이 실행될 때 발생한다. 컴파일은 정상적으로 될수도
* 예외 상활이 발생 -> 에러 정보를 갖고 있는 Exception 객체 생성
* 프로그램이 정상적으로 수행될 수 있도록 Exception 객체 소멸 시켜야 함

### 분류

* Checked Exception : 컴파일 시에 예외 처리를 해 주었는지 체크

  * IOException

* Unchecked Exception : 프로그램 실행 중에 발생하면 Exception

  * Runtime Exception(런타임 에러)
  * ArithmeticException : 0으로 나누는 산술 연산
  * NullPointerException : 참조 데이터형 변수의 값이 null인데 객체에 접근
    * ex) 배열 10칸 만들고 5칸만 객체를 만들면 나머지 5칸은 null
  * ArrayIndexOutOfBoundsException : 배열의 범위를 벗어난 인덱스 접근
  * ClassCastException : 객체의 형 변환 시, 잘못된 클래스로 변환

  

## try - catch - finally

### try

* 예외 상황이 발생할 여지가 있는 코드를 예외 처리
  * try 블록
* Exception이 발생하면 catch문으로 전달

### catch

* 전달 받은 Exception에 따라 블록 안에 코드 실행
* 선언된 Exception에 따라 수행할 일들
* 선언된 Exception이 발생하지 않는 한,  수행하지 않는다
* 보통 예외 변수 e로 사용
  * `e.printStackTrace();` : Exception 정보 확인 가능

```java
try {
	int answer = num1 / num2;
} catch ( ArithmeticException e ) {
	System.out.println("예외 발생");
}
```

* num2가 0이 될 수 있다 -> 예외 처리
  * num2가 0이 되면 "예외 발생" 출력

* 여러 catch문 사용 가능
  * 하위 클래스의 Exception부터 상위 클래스의 Exception 순서로 작성
  * Exception이 발생하면 위에서부터 차례대로 검사하면서 알맞은 catch 블록을 찾아 수행

```java
try {
	Movie movie = null;
	System.out.println( movie.getReleaseDate() );
} catch ( ArithmeticException e ) {
	System.out.println("연산 에러");
} catch ( NullPointerException e ) {
	System.out.println("null 에러”);
} catch ( Exception e ) {
	System.out.println("알 수 없는 에러");
}
```



### finally

* try 블록 안 코드의 Exception 발생 유무와 상관 없이 반드시 수행
* try-catch문 끝나고 블록 밑에 그냥 코드 작성하는 것과 똑같지 않냐
  * try-catch문에서 return해서 프로그램이 종료되면  밑에 적은 것은 실행이 안됨
  * finally문은 실행
  * catch문에서 에러 발생하면서 비정상적으로 프로그램 종료되어도 finally 문 실행



## throws

* 예외가 발생한 지점에서 처리를 어떻게 해야 하는지 모르겠으면 상위 메소드로 Exception을 던짐

* 전달 받은 상위 메소드에서 try catch로 처리하거나 다시 상위 메서드로 던짐

* public Return_type 메서드명 (parameters...)

  ​	throws Exception_type1, Exception_type2.... {

  ​			메서드 내용

  }

* 여러 Exceptions 가능

  * ArithmeticException일 때에도 method1로 던지고, NullPointerException 일 때에도 method1로 던지겠다! -> 가능

```java
public class ThrowsEx {
    public static void main( String[] args ) {
        ThrowsEx ex = new ThrowsEx();
        try {
        	ex.method1();
        } catch ( Exception e ) {
        	System.out.println("예외처리”);
        }
    }
                               
    public void method1() throws Exception {
    	method2();
    }
                               
    public void method2() throws Exception {
    	System.out.println( 10 / 0 );
    }
}
```

* try에서 method1을 실행
* method1에서 method2 실행
* method2에서 Exceptions 발생
* method1으로 throws Exception
* main으로 throws Exception
* catch에서 실행



### throw

* 강제로 Exception 발생시켜 예외 상황을 만듦
* throw new Exception("메세지");
* throw Exception_객체;

```java
public class ThrowExceptionEx {
    public static void main( String[] args ) {
        int k = 3;
        try {
            if ( k < 10 ) {
            	throw new Exception("예외");   
            } else {
                System.out.println("가능~");
            }
        } catch ( Exception e ) {
        	System.out.println( e.getMessage() );
        }
     	}
    }
}
```

* 여기서 쓴거는 기본 Exception 클래스
  * ArithmeticException, NullPointerException 이런거 써도 됨
* k가 10 미만이면 강제로 Exception을 발생시키고, catch 문에서 Exception 객체의 getMessage() 메서드 실행하여 Exception 객체에 세팅한 메시지 반환



## 사용자 정의 예외 클래스

* 제공하는 예외 클래스만으로는 다양한 종료의 예외를 표현하기 어려움
* 제공되어 있는 예외 클래스는 Exception 클래스를 상속받고 있음
* 우리도  Exception 클래스를 상속 받아 새로운 클래스 정의

```java
class PutException extends Exception{
    public PutException(){
        super("유효하지 않은 입력값 입니다.");
    }
}
```

* 생성자에 String을 넣음
* 전달되는 문자열이 getMessage 메서드 호출 시 반환되는 문자열

```java
public static void main(String[] args) {
	try {
		int input = readInput();
		System.out.println(input);
        
	} catch(PutException e){
		System.out.println(e.getMessage());
	}
}

public static int readInput() throws PutException {
	Scanner scanner = new Scanner(System.in);
	int input = scanner.nextInt();
	if(input < 0 ){
		throw new PutException();// 예외상황 발생지점, 예외 던져라~
	}
    return input;
}
```

* 메인에서도 throws 하면 JVM에서 처리

```java
public class AAA throws Exception {
                               
    public void method1() {
    	int age = sc.nextInt();
        if (age < 10){
            throw new Exception("뭐시기");
            System.out.println("여기는 실행 안하고?")
        }
    }
}
```

